win: add dch 536.23
keylase/nvidia-patch pull request #665
Opened 2023-06-15 04:33 UTC by Umgak

**Purpose of proposed changes**
Mostly another version bump.
Something is up with autopatch.py - directing it to an exe outputs an offset off by 400 bytes.

**Essential steps taken**

Generated with autopatch.py, tested with patch-tester.ps1. Readme generated with add_driver.py and readme_autogen.py. The basics.

2023-06-15 06:19 UTC, Umgak commented
I recommend that someone who's actually good at Python and isn't working at 1AM look over the autopatch.py again - my fix feels like a bodge. Could implement detection for whether it's a new-format or old-format archive?

2023-06-16 19:06 UTC, jailuthra requested changes
Thanks @Umgak for figuring this out.

Your changes LGTM, but I'm concerned if someone has to extract or patch an older driver they might not be able to just pass '-T something.dl_` anymore. Maybe we can instead support both modes by adding an if/else check based on the extension of the target?

2023-06-16 19:06 UTC, jailuthra commented on win/tools/autopatch/autopatch.py
> +                    f = fo.read()
```suggestion
                if tgt.endswith(".dll"):
                    with open(tgt, 'rb') as fo:
                        f = fo.read()
                else:
                    f = expand(tgt, sevenzip=sevenzip)
```

2023-06-16 19:09 UTC, jailuthra approved these changes

2023-06-16 19:10 UTC, merged

2023-06-19 07:13 UTC, reloxx13 commented
Thank you very much! Tested today and works 🎉