Add support for driver version 535.104.12
keylase/nvidia-patch pull request #703
Opened 2023-09-27 10:17 UTC by stronk-dev

Running on Ubuntu VM's (22.04.3), apparently had nvidia driver 535.104.12 installed. Applied these changes to patch my drivers

2023-10-02 15:43 UTC, CosmicWebCreator approved these changes

2023-10-03 08:11 UTC, jailuthra commented
Hi, can you update drivers.json and README?

Run these two scripts in `tools/readme-autogen`:
```
./add_driver.py -L 535.104.12 -U <link to driver download>
./readme_autogen.py
```

2023-10-03 08:12 UTC, jailuthra requested changes
Needs update to README and drivers.json

2023-10-03 09:15 UTC, stronk-dev commented
Hope i picked the correct download link. LMK if anything else is required

2023-10-03 09:53 UTC, jailuthra approved these changes

2023-10-03 09:54 UTC, merged